/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package odds.portal.gui;

import java.awt.Dimension;
import java.awt.Panel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Collection;
import java.util.Date;
import java.util.Properties;
import java.util.TreeMap;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

import net.sourceforge.jdatepicker.impl.JDatePanelImpl;
import net.sourceforge.jdatepicker.impl.JDatePickerImpl;
import net.sourceforge.jdatepicker.impl.UtilDateModel;
import odds.portal.OddsPortal;
import odds.portal.Reservation;

/**
 *
 * @author OUba
 */
public class Frame extends javax.swing.JFrame implements ActionListener{

	/**
	 * Creates new form NewJFrame
	 */
	public Frame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		Panel panel = new Panel();
		panel.setPreferredSize(new Dimension(200,200));
		
		JLabel jLabel = new JLabel("Nombre d'années");
		panel.add(jLabel);
		
		Integer[] annees = new Integer[10];
		for(int i=0; i<10; i++) {
			annees[i] = i+1;
		}
        //Create the combo box, select the item at index 4.
        //Indices start at 0, so 4 specifies the pig.
        jAnnees = new JComboBox<Integer>(annees);
        jAnnees.setSelectedIndex(2);
        jAnnees.addActionListener(this);
		panel.add(jAnnees);
		
		
		
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		jButton2.setText("Démarrer");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton2.setPreferredSize(new Dimension(200,150));
		panel.add(jButton2);

		

		
		getContentPane().add(panel);
		pack();
	}// </editor-fold>

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		OddsPortal oddsPortal = gui.getOddsPortal();
		if (oddsPortal == null) {
			oddsPortal = new OddsPortal(gui);
			gui.setBooking(oddsPortal);		
		}
		oddsPortal.start();
		jButton2.setEnabled(false);
		jAnnees.setEnabled(false);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Frame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	// private javax.swing.JPanel datePanel;
	private javax.swing.JButton jButton2;
	JComboBox<Integer> jAnnees;
	Gui gui;

	public void initialiserDatePicker() {

	}

	public Gui getGui() {
		return gui;
	}

	public void setGui(Gui gui) {
		this.gui = gui;
	}

	public void actionPerformed(ActionEvent e) {
        JComboBox<Integer> cb = (JComboBox<Integer>)e.getSource();
        Integer nbAnnees = (Integer) cb.getSelectedItem();
        gui.getOddsPortal().setNbAnnees(nbAnnees);
	}

}
